version: '3.2'

services:
  database:
    image: mariadb:10.3
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql

  http:
    image: nginx:1.13.12-alpine
    depends_on:
      - php
    env_file:
      - .env
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public/:/srv/public/:ro

  php:
    build:
      context: ./docker/php
    working_dir: /srv
    env_file:
      - .env
    volumes:
      - ./:/srv/

volumes:
  database: ~
